/**
 */
package edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.provider;

import edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.util.SolidityContractsAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class SolidityContractsItemProviderAdapterFactory extends SolidityContractsAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SolidityContractsItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.EventParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EventParameterItemProvider eventParameterItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.EventParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEventParameterAdapter() {
		if (eventParameterItemProvider == null) {
			eventParameterItemProvider = new EventParameterItemProvider(this);
		}

		return eventParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.CustomArray} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CustomArrayItemProvider customArrayItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.CustomArray}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCustomArrayAdapter() {
		if (customArrayItemProvider == null) {
			customArrayItemProvider = new CustomArrayItemProvider(this);
		}

		return customArrayItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.ModifierParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModifierParameterItemProvider modifierParameterItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.ModifierParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModifierParameterAdapter() {
		if (modifierParameterItemProvider == null) {
			modifierParameterItemProvider = new ModifierParameterItemProvider(this);
		}

		return modifierParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.StateVariable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StateVariableItemProvider stateVariableItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.StateVariable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStateVariableAdapter() {
		if (stateVariableItemProvider == null) {
			stateVariableItemProvider = new StateVariableItemProvider(this);
		}

		return stateVariableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.Enum} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumItemProvider enumItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.Enum}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumAdapter() {
		if (enumItemProvider == null) {
			enumItemProvider = new EnumItemProvider(this);
		}

		return enumItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.Event} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EventItemProvider eventItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.Event}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEventAdapter() {
		if (eventItemProvider == null) {
			eventItemProvider = new EventItemProvider(this);
		}

		return eventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.EnumMember} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumMemberItemProvider enumMemberItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.EnumMember}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumMemberAdapter() {
		if (enumMemberItemProvider == null) {
			enumMemberItemProvider = new EnumMemberItemProvider(this);
		}

		return enumMemberItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.Mapping} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MappingItemProvider mappingItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.Mapping}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMappingAdapter() {
		if (mappingItemProvider == null) {
			mappingItemProvider = new MappingItemProvider(this);
		}

		return mappingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.Modifier} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModifierItemProvider modifierItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.Modifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModifierAdapter() {
		if (modifierItemProvider == null) {
			modifierItemProvider = new ModifierItemProvider(this);
		}

		return modifierItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.StructMember} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StructMemberItemProvider structMemberItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.StructMember}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStructMemberAdapter() {
		if (structMemberItemProvider == null) {
			structMemberItemProvider = new StructMemberItemProvider(this);
		}

		return structMemberItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.Repository} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RepositoryItemProvider repositoryItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.Repository}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRepositoryAdapter() {
		if (repositoryItemProvider == null) {
			repositoryItemProvider = new RepositoryItemProvider(this);
		}

		return repositoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.Constructor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConstructorItemProvider constructorItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.Constructor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConstructorAdapter() {
		if (constructorItemProvider == null) {
			constructorItemProvider = new ConstructorItemProvider(this);
		}

		return constructorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.PrimitiveType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrimitiveTypeItemProvider primitiveTypeItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.PrimitiveType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrimitiveTypeAdapter() {
		if (primitiveTypeItemProvider == null) {
			primitiveTypeItemProvider = new PrimitiveTypeItemProvider(this);
		}

		return primitiveTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.ReturnVariable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReturnVariableItemProvider returnVariableItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.ReturnVariable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReturnVariableAdapter() {
		if (returnVariableItemProvider == null) {
			returnVariableItemProvider = new ReturnVariableItemProvider(this);
		}

		return returnVariableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.Struct} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StructItemProvider structItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.Struct}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStructAdapter() {
		if (structItemProvider == null) {
			structItemProvider = new StructItemProvider(this);
		}

		return structItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.Contract} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContractItemProvider contractItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.Contract}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContractAdapter() {
		if (contractItemProvider == null) {
			contractItemProvider = new ContractItemProvider(this);
		}

		return contractItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.FunctionParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionParameterItemProvider functionParameterItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.FunctionParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionParameterAdapter() {
		if (functionParameterItemProvider == null) {
			functionParameterItemProvider = new FunctionParameterItemProvider(this);
		}

		return functionParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.ConstructorParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConstructorParameterItemProvider constructorParameterItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.ConstructorParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConstructorParameterAdapter() {
		if (constructorParameterItemProvider == null) {
			constructorParameterItemProvider = new ConstructorParameterItemProvider(this);
		}

		return constructorParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.DefaultArray} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DefaultArrayItemProvider defaultArrayItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.DefaultArray}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDefaultArrayAdapter() {
		if (defaultArrayItemProvider == null) {
			defaultArrayItemProvider = new DefaultArrayItemProvider(this);
		}

		return defaultArrayItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.FunctionType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionTypeItemProvider functionTypeItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.FunctionType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionTypeAdapter() {
		if (functionTypeItemProvider == null) {
			functionTypeItemProvider = new FunctionTypeItemProvider(this);
		}

		return functionTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.ContractType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContractTypeItemProvider contractTypeItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.ContractType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContractTypeAdapter() {
		if (contractTypeItemProvider == null) {
			contractTypeItemProvider = new ContractTypeItemProvider(this);
		}

		return contractTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.OverrideFunction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OverrideFunctionItemProvider overrideFunctionItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.OverrideFunction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOverrideFunctionAdapter() {
		if (overrideFunctionItemProvider == null) {
			overrideFunctionItemProvider = new OverrideFunctionItemProvider(this);
		}

		return overrideFunctionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.LocalFunction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LocalFunctionItemProvider localFunctionItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.LocalFunction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLocalFunctionAdapter() {
		if (localFunctionItemProvider == null) {
			localFunctionItemProvider = new LocalFunctionItemProvider(this);
		}

		return localFunctionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.GlobalFunction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GlobalFunctionItemProvider globalFunctionItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.sdq.soliditymetamodel.soliditycontracts.GlobalFunction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGlobalFunctionAdapter() {
		if (globalFunctionItemProvider == null) {
			globalFunctionItemProvider = new GlobalFunctionItemProvider(this);
		}

		return globalFunctionItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (eventParameterItemProvider != null) eventParameterItemProvider.dispose();
		if (customArrayItemProvider != null) customArrayItemProvider.dispose();
		if (modifierParameterItemProvider != null) modifierParameterItemProvider.dispose();
		if (stateVariableItemProvider != null) stateVariableItemProvider.dispose();
		if (enumItemProvider != null) enumItemProvider.dispose();
		if (eventItemProvider != null) eventItemProvider.dispose();
		if (enumMemberItemProvider != null) enumMemberItemProvider.dispose();
		if (mappingItemProvider != null) mappingItemProvider.dispose();
		if (modifierItemProvider != null) modifierItemProvider.dispose();
		if (structMemberItemProvider != null) structMemberItemProvider.dispose();
		if (repositoryItemProvider != null) repositoryItemProvider.dispose();
		if (constructorItemProvider != null) constructorItemProvider.dispose();
		if (primitiveTypeItemProvider != null) primitiveTypeItemProvider.dispose();
		if (returnVariableItemProvider != null) returnVariableItemProvider.dispose();
		if (structItemProvider != null) structItemProvider.dispose();
		if (contractItemProvider != null) contractItemProvider.dispose();
		if (functionParameterItemProvider != null) functionParameterItemProvider.dispose();
		if (constructorParameterItemProvider != null) constructorParameterItemProvider.dispose();
		if (defaultArrayItemProvider != null) defaultArrayItemProvider.dispose();
		if (functionTypeItemProvider != null) functionTypeItemProvider.dispose();
		if (contractTypeItemProvider != null) contractTypeItemProvider.dispose();
		if (overrideFunctionItemProvider != null) overrideFunctionItemProvider.dispose();
		if (localFunctionItemProvider != null) localFunctionItemProvider.dispose();
		if (globalFunctionItemProvider != null) globalFunctionItemProvider.dispose();
	}

}
